version: 0.2
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR for region ${AWSRegion}
            - eval $(aws ecr get-login --no-include-email --region ${AWSRegion})
            - echo "Getting ENV file from Secrets cat/${AppName}-${AppEnv}/core"
            - aws secretsmanager get-secret-value --secret-id "cat/${AppName}-${AppEnv}/core" --query SecretString --output text --region eu-west-1 > .env
            - echo "Getting Core Env Settings"
            - printf "\n# ENV CORE SETTINGS\n" >> .env
            - aws secretsmanager get-secret-value --secret-id "cat/env/core" --query SecretString --output text --region eu-west-1 >> .env
            - printf "\n# END ENV CORE SETTINGS\n" >> .env
            - echo "Getting your env additions"
            - printf "\n# ENV ADDITIONS\n" >> .env
            - aws secretsmanager get-secret-value --secret-id "cat/${AppName}-${AppEnv}/additions" --query SecretString --output text --region eu-west-1 >> .env
            - printf "\n# END ENV ADDITIONS\n" >> .env
            - sed -e "s/APP_ENV/${AppEnv}/g" -e "s/APP_NAME/${AppName}/g"  filebeat-template.yml > filebeat.yml
            - cp supervisor-production.ini supervisor.ini
            - cp default-production.conf default.conf
    build:
        commands:
            - printf '[{"name":"%s-%s","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s_%s"}]' $AppName $AppEnv $AWSAccountId $AWSRegion $AppName $AppEnv $HASH > imagedefinitions.json
            - docker build -t ${AppName} .
            - HASH=$(git rev-parse HEAD)
            - docker tag ${AppName}:latest ${AWSAccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${AppName}:${AppEnv}_$HASH
    post_build:
        commands:
            - HASH=$(git rev-parse HEAD)
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push ${AWSAccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${AppName}:${AppEnv}_$HASH
artifacts:
    files: imagedefinitions.json
