name: Snyk PR Automerge
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  automerge:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "contains(github.event.pull_request.title, '[Snyk]')"
    steps:
      - name: Wait for status checks
        id: status_check
        uses: WyriHaximus/github-action-wait-for-status@master
        with:
          ignoreActions: automerge
          checkInterval: 60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve PR
        uses: actions/github-script@v2
        if: steps.status_check.outputs.status == 'success'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const title = context.payload.pull_request.title
            const pr_number = context.payload.pull_request.number

            github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            }).then(results => {
              const how_many = results.data.length
              if(how_many < 1) {
                github.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr_number,
                  body: "This is a security patch so it's automatically approved",
                  event: "APPROVE"
                })
              }
            })
      - name: Label PR as Automerge and Security
        uses: TimonVS/pr-labeler-action@v3
        if: steps.status_check.outputs.status == 'success'
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge
        uses: actions/github-script@v2
        if: steps.status_check.outputs.status == 'success'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr_number = context.payload.pull_request.number
            const title = context.payload.pull_request.title

            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              commit_message: "Applied Snyk security updates",
              commit_title: "Snyk PR",
              merge_method: "merge"
            })
