name: Validate nginx configuration

on:
  pull_request:

jobs:
  validate_nginx_config:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code (PR)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout stratus-core-docker
        uses: actions/checkout@v2
        with:
          repository: pfizer/stratus-core-docker
          token: '${{ secrets.STRATUS_GITHUB_TOKEN }}'
          path: core-docker
          ref: master
          fetch-depth: 1

      - name: Validate staging nginx configuration
        id: validate-nginx-config-staging
        run: |
          docker run --rm -t -a stdout --name nginx-validate -v $PWD/:/app -v $PWD/core-docker:/core-docker -v $PWD/default.conf:/etc/nginx/sites-enabled/default.conf -v $PWD/core-docker/nginx.conf:/etc/nginx/nginx.conf -v $PWD/core-docker/nginx.crt:/etc/nginx/ssl/nginx.crt -v $PWD/core-docker/nginx.key:/etc/nginx/ssl/nginx.key nginx:latest nginx -c /etc/nginx/nginx.conf -t

      - name: Validate production nginx configuration
        id: validate-nginx-config-prod
        run: |
          docker run --rm -t -a stdout --name nginx-validate -v $PWD/:/app -v $PWD/core-docker:/core-docker -v $PWD/default-production.conf:/etc/nginx/sites-enabled/default-production.conf -v $PWD/core-docker/nginx.conf:/etc/nginx/nginx.conf -v $PWD/core-docker/nginx.crt:/etc/nginx/ssl/nginx.crt -v $PWD/core-docker/nginx.key:/etc/nginx/ssl/nginx.key nginx:latest nginx -c /etc/nginx/nginx.conf -t
